"""init schema

Revision ID: 1b0e6089052d
Revises: 
Create Date: 2026-05-13 23:21:02.626216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1b0e6089052d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('OOO', 'IP', name='company_type_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_table('dds_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('IN', 'OUT', 'TRANSFER', name='dds_type_enum'), nullable=False),
    sa.Column('priority_default', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dds_categories_code'), 'dds_categories', ['code'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('bank', sa.Enum('TOCHKA', 'TBANK', 'ALFA', name='bank_enum'), nullable=False),
    sa.Column('account_type', sa.Enum('MAIN', 'TAX', 'DBP', 'CASH', name='account_type_enum'), nullable=False),
    sa.Column('account_number', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number')
    )
    op.create_index(op.f('ix_accounts_bank'), 'accounts', ['bank'], unique=False)
    op.create_index(op.f('ix_accounts_company_id'), 'accounts', ['company_id'], unique=False)
    op.create_table('payment_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('counterparty', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'PAID', 'DEFERRED', name='payment_status_enum'), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_queue_company_id'), 'payment_queue', ['company_id'], unique=False)
    op.create_index(op.f('ix_payment_queue_counterparty'), 'payment_queue', ['counterparty'], unique=False)
    op.create_index(op.f('ix_payment_queue_due_date'), 'payment_queue', ['due_date'], unique=False)
    op.create_index(op.f('ix_payment_queue_priority'), 'payment_queue', ['priority'], unique=False)
    op.create_index(op.f('ix_payment_queue_status'), 'payment_queue', ['status'], unique=False)
    op.create_table('balances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.Enum('API', 'MANUAL', name='balance_source_enum'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balances_account_id'), 'balances', ['account_id'], unique=False)
    op.create_index(op.f('ix_balances_recorded_at'), 'balances', ['recorded_at'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('direction', sa.Enum('IN', 'OUT', name='transaction_direction_enum'), nullable=False),
    sa.Column('counterparty', sa.String(length=255), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('dds_category', sa.String(length=128), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_counterparty'), 'transactions', ['counterparty'], unique=False)
    op.create_index(op.f('ix_transactions_dds_category'), 'transactions', ['dds_category'], unique=False)
    op.create_index(op.f('ix_transactions_external_id'), 'transactions', ['external_id'], unique=True)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_external_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_dds_category'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_counterparty'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_balances_recorded_at'), table_name='balances')
    op.drop_index(op.f('ix_balances_account_id'), table_name='balances')
    op.drop_table('balances')
    op.drop_index(op.f('ix_payment_queue_status'), table_name='payment_queue')
    op.drop_index(op.f('ix_payment_queue_priority'), table_name='payment_queue')
    op.drop_index(op.f('ix_payment_queue_due_date'), table_name='payment_queue')
    op.drop_index(op.f('ix_payment_queue_counterparty'), table_name='payment_queue')
    op.drop_index(op.f('ix_payment_queue_company_id'), table_name='payment_queue')
    op.drop_table('payment_queue')
    op.drop_index(op.f('ix_accounts_company_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_bank'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_dds_categories_code'), table_name='dds_categories')
    op.drop_table('dds_categories')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
