"""company slug/description, account bank nullable

Revision ID: 54311550a030
Revises: 1b0e6089052d
Create Date: 2026-05-14 11:22:19.338231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '54311550a030'
down_revision: Union[str, None] = '1b0e6089052d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'bank',
               existing_type=postgresql.ENUM('TOCHKA', 'TBANK', 'ALFA', name='bank_enum'),
               nullable=True)
    op.add_column('companies', sa.Column('slug', sa.String(length=64), nullable=True))
    op.add_column('companies', sa.Column('description', sa.Text(), nullable=True))
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_column('companies', 'description')
    op.drop_column('companies', 'slug')
    op.alter_column('accounts', 'bank',
               existing_type=postgresql.ENUM('TOCHKA', 'TBANK', 'ALFA', name='bank_enum'),
               nullable=False)
    # ### end Alembic commands ###
